LOAD DATA LOCAL INFILE 'H:/tmp//students.txt' REPLACE INTO TABLE students
CHARACTER SET cp1251;

LOAD DATA LOCAL INFILE 'H:/tmp//subjects.txt' REPLACE INTO TABLE subjects
CHARACTER SET cp1251;

LOAD DATA LOCAL INFILE 'H:/tmp//exam.txt' REPLACE INTO TABLE exam
CHARACTER SET cp1251